### ISSUE TITLE
error Posting data 

### ISSUE THREAD

**Issue by Rautabout** [Samorange1/Connect-ESP32-with-Firebase-via-GSM#1]
Hi,

I followed your code and managed to connect to server via Arduino, however when I try to post data I get a 400 Bad Request error.
Could you help, please?
[sketch_jan13a.txt](https://github.com/Samorange1/Connect-ESP32-to-Firebase-via-GSM/files/7858661/sketch_jan13a.txt)

#edit
Issue fixed

**Comment by madhavr08** [comment]
Hey!.. Did you solve it?
